param(
    [switch]$NoMenu,
    [switch]$RegenerateConfig
)
#ParamStating In
$ErrorActionPreference = "Stop"
#Oh Dear we gonna start
#                       :)
$GameDir = $PSScriptRoot
$SettingsPath = Join-Path $GameDir "imustafski-runner-settings.json"
$LegacySettingsPaths = @(
    (Join-Path $GameDir "moh-server-settings.json")
)
$GeneratedConfigName = "imustafski-server.cfg"
$GeneratedConfigPath = Join-Path $GameDir "main\$GeneratedConfigName"
$PlayerConfigPath = Join-Path $GameDir "main\configs\unnamedsoldier.cfg"
$AutoexecPath = Join-Path $GameDir "main\autoexec.cfg"
$script:LastFriendCommand = ""
#Server Config Settings will be placed in the main (dir)
function Get-DefaultSettings {
    [pscustomobject]@{
        ServerName = "IMUSTAFSKI standard server"
        Password = ""
        MapRotation = @("dm/mohdm6") #changeable via the tui(done)
        TimeLimit = 20 #in minutes will be explained later in the tui(done)
        MaxPlayers = 8
        Port = 12203 #default(changeable) tui
        GameType = 1
        Cheats = 0
        PlayerSpeed = 320
        Gravity = 800
        Knockback = 1000
        WeaponRespawn = 5
        ResolutionWidth = 1920
        ResolutionHeight = 1080
        Fullscreen = 1
        ColorBits = 32
        TextureBits = 32
        TextureCompression = 0
        PicMip = 0
        TextureMode = "gl_linear_mipmap_linear"
        FastSky = 0
        ConsoleEnabled = 1
        DeveloperMode = 0
        Fov = 90
        ServerExeName = "MOHAA_server.exe"
        GameExeName = "MOHAA.exe"
    }
}
# All settings now can be edited through the tui directly not via editing the powershell so now the project is just maybe if you can learn somthing :) if you are a normal user just run the powershell script in the main game folder
function Normalize-Settings($Settings) {
    $defaults = Get-DefaultSettings
    foreach ($property in $defaults.PSObject.Properties.Name) {
        if (-not ($Settings.PSObject.Properties.Name -contains $property) -or $null -eq $Settings.$property) {
            $Settings | Add-Member -NotePropertyName $property -NotePropertyValue $defaults.$property -Force
        }
    }

    $maps = @($Settings.MapRotation | Where-Object { $_ -and $_.Trim() })
    if ($maps.Count -eq 0) { $maps = @("dm/mohdm6") }
    $Settings.MapRotation = $maps
    return $Settings
}

function Read-Settings {
    if (-not (Test-Path $SettingsPath)) {
        $legacy = $LegacySettingsPaths | Where-Object { Test-Path $_ } | Select-Object -First 1
        if ($legacy) {
            Copy-Item -LiteralPath $legacy -Destination $SettingsPath -Force
        }
    }

    if (-not (Test-Path $SettingsPath)) {
        $settings = Get-DefaultSettings
        Save-Settings $settings
        return $settings
    }

    try {
        $settings = Normalize-Settings (Get-Content -Raw $SettingsPath | ConvertFrom-Json)
        Save-Settings $settings
        return $settings
    } catch {
        $backup = "$SettingsPath.broken"
        Move-Item -LiteralPath $SettingsPath -Destination $backup -Force
        $settings = Get-DefaultSettings
        Save-Settings $settings
        return $settings
    }
}
# ;)
function Save-Settings($Settings) {
    $Settings | ConvertTo-Json -Depth 5 | Set-Content -LiteralPath $SettingsPath -Encoding ASCII
}

function Copy-Settings($Settings) {
    $Settings | ConvertTo-Json -Depth 5 | ConvertFrom-Json
}

function Escape-CfgValue([string]$Value) {
    if ($null -eq $Value) { return "" }
    return ($Value -replace '\\', '\\' -replace '"', '\"')
}

function Get-PrimaryMap($Settings) {
    @($Settings.MapRotation)[0]
}

function Get-MapList($Settings) {
    (@($Settings.MapRotation) -join " ")
}

function Write-ServerConfig($Settings, [switch]$Force) {
    if ((Test-Path $GeneratedConfigPath) -and -not $Force) {
        return "Existing"
    }

    $safeServerName = Escape-CfgValue $Settings.ServerName
    $safePassword = Escape-CfgValue $Settings.Password
    $safeMapList = Escape-CfgValue (Get-MapList $Settings)
    $safePrimaryMap = Escape-CfgValue (Get-PrimaryMap $Settings)

    $cfg = @"
// Generated by IMUSTAFSKI Server Runner.
// Use Server Settings inside the launcher, then Apply to rebuild this file.

seta sv_hostname "$safeServerName"
seta sv_maxclients "$($Settings.MaxPlayers)"
seta sv_maxRate "10000"
seta sv_timeout "120"
seta sv_precache "1"
seta sv_fps "30"
seta sv_reconnectlimit "3"
seta sv_chatter "1"
seta logfile "2"
seta net_noipx "1"
seta sv_cheats "$($Settings.Cheats)"
# :)    :)  ;0
// 1=Deathmatch, 2=Team match, 3=Objective, 4=Roundbased
seta g_gametype "$($Settings.GameType)"
seta timelimit "$($Settings.TimeLimit)"
seta fraglimit "0"
seta g_password "$safePassword"

// Gameplay tuning
seta g_speed "$($Settings.PlayerSpeed)"
seta g_gravity "$($Settings.Gravity)"
seta g_knockback "$($Settings.Knockback)"
seta g_weaponRespawn "$($Settings.WeaponRespawn)"

// Multiple maps rotate after the timelimit. One map stays on that map.
seta sv_maplist "$safeMapList"
map $safePrimaryMap
"@

    Set-Content -LiteralPath $GeneratedConfigPath -Value $cfg -Encoding ASCII
    return "Generated"
}

function Set-CfgValue([string]$Path, [string]$Name, [string]$Value) {
    if (-not (Test-Path $Path)) {
        New-Item -ItemType File -Path $Path -Force | Out-Null
    }

    $lines = @(Get-Content -LiteralPath $Path -ErrorAction SilentlyContinue)
    $escapedName = [regex]::Escape($Name)
    $replacement = "seta $Name `"$Value`""
    $found = $false

    for ($i = 0; $i -lt $lines.Count; $i++) {
        if ($lines[$i] -match "^\s*seta\s+$escapedName\s+") {
            $lines[$i] = $replacement
            $found = $true
        }
    }

    if (-not $found) {
        $lines += $replacement
    }

    Set-Content -LiteralPath $Path -Value $lines -Encoding ASCII
}

function Backup-PlayerConfig {
    if ((Test-Path $PlayerConfigPath) -and -not (Test-Path "$PlayerConfigPath.imustafski-backup")) {
        Copy-Item -LiteralPath $PlayerConfigPath -Destination "$PlayerConfigPath.imustafski-backup" -Force
    }
}
#Game settings direct in the tui
function Apply-GameSettings($Settings) {
    Backup-PlayerConfig

    $values = [ordered]@{
        r_mode = "-1"
        r_customwidth = "$($Settings.ResolutionWidth)"
        r_customheight = "$($Settings.ResolutionHeight)"
        r_fullscreen = "$($Settings.Fullscreen)"
        r_colorbits = "$($Settings.ColorBits)"
        r_texturebits = "$($Settings.TextureBits)"
        r_ext_compressed_textures = "$($Settings.TextureCompression)"
        r_picmip = "$($Settings.PicMip)"
        r_textureMode = "$($Settings.TextureMode)"
        r_fastsky = "$($Settings.FastSky)"
        ui_console = "$($Settings.ConsoleEnabled)"
        developer = "$($Settings.DeveloperMode)"
        cg_fov = "$($Settings.Fov)"
    }

    foreach ($item in $values.GetEnumerator()) {
        Set-CfgValue $PlayerConfigPath $item.Key $item.Value
        Set-CfgValue $AutoexecPath $item.Key $item.Value
    }

    return "Game settings applied to main\configs\unnamedsoldier.cfg and main\autoexec.cfg."
}

function Get-ServerProcess($Settings) {
    $serverPath = Join-Path $GameDir $Settings.ServerExeName
    $exeName = [IO.Path]::GetFileNameWithoutExtension($Settings.ServerExeName)
    Get-Process -Name $exeName -ErrorAction SilentlyContinue | Where-Object {
        try { $_.Path -eq $serverPath } catch { $false }
    }
}

function Start-Server($Settings, [switch]$ForceConfig) {
    $serverExe = Join-Path $GameDir $Settings.ServerExeName
    if (-not (Test-Path $serverExe)) {
        throw "Missing server executable: $serverExe"
    }

    $configState = Write-ServerConfig $Settings -Force:$ForceConfig
    $running = Get-ServerProcess $Settings
    if ($running) {
        return [pscustomobject]@{
            Process = $running | Select-Object -First 1
            ConfigState = $configState
        }
    }
    #Setting the exe ending in Properties
    $args = @(
        "+set", "dedicated", "2",
        "+set", "net_port", "$($Settings.Port)",
        "+set", "net_noipx", "1",
        "+exec", $GeneratedConfigName
    )

    [void](Start-Process -FilePath $serverExe -ArgumentList $args -WorkingDirectory $GameDir -PassThru)
    Start-Sleep -Seconds 2

    return [pscustomobject]@{
        Process = Get-ServerProcess $Settings | Select-Object -First 1
        ConfigState = $configState
    }
}

function Stop-Server($Settings) {
    $running = Get-ServerProcess $Settings
    if (-not $running) { return }
    $running | ForEach-Object {
        $_.CloseMainWindow() | Out-Null
        Start-Sleep -Milliseconds 800
        if (-not $_.HasExited) {
            Stop-Process -Id $_.Id -Force
        }
    }
}
                        #As shown it will get the LocalIP
function Get-LocalIPv4Addresses {
    try {
        return Get-NetIPAddress -AddressFamily IPv4 -ErrorAction Stop |
            Where-Object {
                $_.IPAddress -ne "127.0.0.1" -and
                $_.IPAddress -notlike "169.254.*" -and
                $_.PrefixOrigin -ne "WellKnown"
            } |
            Sort-Object InterfaceAlias, IPAddress |
            Select-Object InterfaceAlias, IPAddress
    } catch {
        return [System.Net.Dns]::GetHostAddresses($env:COMPUTERNAME) |
            Where-Object { $_.AddressFamily -eq "InterNetwork" -and $_.IPAddressToString -ne "127.0.0.1" } |
            ForEach-Object { [pscustomobject]@{ InterfaceAlias = "Network"; IPAddress = $_.IPAddressToString } }
    }
}
                        #Here you can set any service to inspect the ip address that you want   
function Get-PublicIP {
    $services = @(
        "https://api.ipify.org",
        "https://ifconfig.me/ip",
        "https://icanhazip.com"
    )

    foreach ($service in $services) {
        try {
            $ip = (Invoke-RestMethod -Uri $service -TimeoutSec 4).ToString().Trim()
            if ($ip -match '^\d{1,3}(\.\d{1,3}){3}$') {
                return $ip
            }
        } catch {
        }
    }
    return $null
}
 #done fetching
function Test-LocalServerBinding($Settings, $Process) {
    if (-not $Process) {
        return $false
    }

    try {
        $pattern = "^\s*UDP\s+\S+:$($Settings.Port)\s+\*:\*\s+$($Process.Id)\s*$"
        return [bool](netstat -ano -p udp | Select-String -Pattern $pattern)
    } catch {
        return $false
    }
}

function Test-LocalServer($Settings, $Process) {
    if (Test-LocalServerBinding $Settings $Process) {
        return "OK - listening on UDP 0.0.0.0:$($Settings.Port)"
    }
    return "WARN - process is running, but UDP $($Settings.Port) was not detected"
}

function Get-ConnectionInfo($Settings) {
    $publicIp = Get-PublicIP #SetUp the IP that is given from the service 
    $localIps = @(Get-LocalIPv4Addresses) #setting the LocalIP for the hoster
    $publicCommand = if ($publicIp) { "connect ${publicIp}:$($Settings.Port)" } else { "" }
    $vpnCommand = if ($localIps.Count -gt 0) { "connect $($localIps[0].IPAddress):$($Settings.Port)" } else { "" }
    $friendCommand = if ($publicCommand) { $publicCommand } else { $vpnCommand }
    $script:LastFriendCommand = $friendCommand

    [pscustomobject]@{
        PublicIP = $publicIp
        LocalIPs = $localIps
        PublicCommand = $publicCommand
        VpnCommand = $vpnCommand
        FriendCommand = $friendCommand
        HostCommand = "connect 127.0.0.1:$($Settings.Port)"
    }
}

function Write-LabelValue([string]$Label, [string]$Value, [ConsoleColor]$Color = [ConsoleColor]::Gray) {
    Write-Host ("  {0,-13}" -f $Label) -NoNewline -ForegroundColor DarkGray
    Write-Host $Value -ForegroundColor $Color
}
# TUI
function Show-Dashboard($Settings, $Process, $ConfigState, [string]$Message = "") {
    $connection = Get-ConnectionInfo $Settings
    $status = if ($Process -and -not $Process.HasExited) { "Running, PID $($Process.Id)" } else { "Not running" }
    $test = if ($Process -and -not $Process.HasExited) { Test-LocalServer $Settings $Process } else { "Not tested" }
    $statusColor = if ($status -like "Running*") { [ConsoleColor]::Green } else { [ConsoleColor]::Red }
    $testColor = if ($test -like "OK*") { [ConsoleColor]::Green } else { [ConsoleColor]::Yellow }
    $rotationLabel = if (@($Settings.MapRotation).Count -gt 1) { "$(Get-PrimaryMap $Settings) + $(@($Settings.MapRotation).Count - 1) queued" } else { Get-PrimaryMap $Settings }

    Clear-Host
    Write-Host ""
    Write-Host "  IMUSTAFSKI Server Runner" -ForegroundColor Cyan
    Write-Host "  =====================================" -ForegroundColor DarkCyan
    Write-LabelValue "Status" $status $statusColor
    Write-LabelValue "Name" $Settings.ServerName Cyan
    Write-LabelValue "Map queue" $rotationLabel Gray
    Write-LabelValue "Time limit" "$($Settings.TimeLimit) minutes" Gray
    Write-LabelValue "Port" "UDP $($Settings.Port)" Gray
    Write-LabelValue "Gameplay" "speed $($Settings.PlayerSpeed), gravity $($Settings.Gravity), cheats $($Settings.Cheats)" Gray
    Write-LabelValue "Game video" "$($Settings.ResolutionWidth)x$($Settings.ResolutionHeight), textures $($Settings.TextureBits)-bit" Gray
    Write-LabelValue "Test" $test $testColor
    Write-LabelValue "Config" "$GeneratedConfigName ($ConfigState)" DarkGray
    Write-Host ""
    Write-Host "  SEND THIS TO Your FRIEND-S" -ForegroundColor Yellow
    Write-Host "  --------------------" -ForegroundColor DarkYellow
    if ($connection.PublicCommand) {
        Write-Host "  Internet command, after router port-forward:" -ForegroundColor DarkGray
        Write-Host "  $($connection.PublicCommand)" -ForegroundColor Yellow
    } else {
        Write-Host "  Public IP was not detected. Use LAN/VPN below or check internet." -ForegroundColor Yellow
    }
    Write-Host ""
    Write-Host "  LAN / VPN" -ForegroundColor Cyan
    if ($connection.LocalIPs.Count -gt 0) {
        $connection.LocalIPs | ForEach-Object {
            Write-Host ("  connect {0}:{1}    {2}" -f $_.IPAddress, $Settings.Port, $_.InterfaceAlias) -ForegroundColor Gray
        }
    } else {
        Write-Host "  No LAN/VPN IPv4 address detected." -ForegroundColor Yellow
    }
    Write-Host ""
    Write-Host "  HOST CONNECTS WITH" -ForegroundColor Green
    Write-Host "  $($connection.HostCommand)" -ForegroundColor Green
    Write-Host ""
    Write-Host "  In MOHAA press ~, type the connect command, then press Enter." -ForegroundColor DarkGray
    Write-Host "  Public internet play requires UDP $($Settings.Port) forwarded to this PC." -ForegroundColor DarkGray
    if ($Message) {
        Write-Host ""
        Write-Host "  $Message" -ForegroundColor Magenta
    }
}
# Game Opening Direct from the TUI
function Open-Game($Settings) {
    $gameExe = Join-Path $GameDir $Settings.GameExeName
    if (-not (Test-Path $gameExe)) {
        return "Missing game executable: $gameExe"
    }
    Start-Process -FilePath $gameExe -WorkingDirectory $GameDir
    return "MOHAA launched."
}
#clipboard direct tui
function Copy-FriendCommand {
    if (-not $script:LastFriendCommand) {
        return "No friend command is available yet."
    }

    try {
        Set-Clipboard -Value $script:LastFriendCommand
        return "Copied to clipboard: $script:LastFriendCommand"
    } catch {
        return "Copy failed. Send this manually: $script:LastFriendCommand"
    }
}
#stuff I Guess
function Invoke-ArrowMenu($Items, [string]$Hint = "Use Up/Down arrows, Enter to choose. Hotkeys also work.") {
    $selected = 0
    while ($true) {
        Write-Host ""
        Write-Host "  $Hint" -ForegroundColor DarkGray
        for ($i = 0; $i -lt $Items.Count; $i++) {
            $prefix = if ($i -eq $selected) { "> " } else { "  " }
            $color = if ($i -eq $selected) { [ConsoleColor]::Black } else { [ConsoleColor]::Gray }
            $background = if ($i -eq $selected) { [ConsoleColor]::Cyan } else { [ConsoleColor]::Black }
            Write-Host ("  {0}{1}" -f $prefix, $Items[$i].Label) -ForegroundColor $color -BackgroundColor $background
        }

        $key = [Console]::ReadKey($true)
        switch ($key.Key) {
            "UpArrow" {
                if ($selected -gt 0) { $selected-- } else { $selected = $Items.Count - 1 }
            }
            "DownArrow" {
                if ($selected -lt ($Items.Count - 1)) { $selected++ } else { $selected = 0 }
            }
            "Enter" {
                return $Items[$selected].Action
            }
            default {
                $match = $Items | Where-Object { $_.Hotkey -eq $key.KeyChar.ToString().ToUpperInvariant() } | Select-Object -First 1
                if ($match) { return $match.Action }
            }
        }

        [Console]::SetCursorPosition(0, [Console]::CursorTop - ($Items.Count + 2))
    }
}

function Read-SettingText([string]$Prompt, [string]$CurrentValue) {
    Write-Host ""
    Write-Host "  $Prompt" -ForegroundColor Cyan
    Write-Host "  Current: $CurrentValue" -ForegroundColor DarkGray
    $value = Read-Host "  New value, blank keeps current"
    if ([string]::IsNullOrWhiteSpace($value)) { return $CurrentValue }
    return $value.Trim()
}

function Read-SettingInt([string]$Prompt, [int]$CurrentValue, [int]$Min, [int]$Max) {
    while ($true) {
        $value = Read-SettingText $Prompt "$CurrentValue"
        $parsed = 0
        if ([int]::TryParse($value, [ref]$parsed) -and $parsed -ge $Min -and $parsed -le $Max) {
            return $parsed
        }
        Write-Host "  Enter a number from $Min to $Max." -ForegroundColor Yellow
    }
}
#screen settings
function Show-SettingsScreen($Draft, [string]$Message = "") {
    Clear-Host
    Write-Host ""
    Write-Host "  SERVER SETTINGS" -ForegroundColor Cyan
    Write-Host "  =====================================" -ForegroundColor DarkCyan
    Write-LabelValue "Name" $Draft.ServerName Cyan
    Write-LabelValue "Password" $(if ($Draft.Password) { "(set)" } else { "(none)" }) Gray
    Write-LabelValue "Maps" (Get-MapList $Draft) Gray
    Write-LabelValue "Rotation" $(if (@($Draft.MapRotation).Count -gt 1) { "Rotates after timelimit" } else { "Single map, stays on same map" }) Gray
    Write-LabelValue "Time limit" "$($Draft.TimeLimit) minutes" Gray
    Write-LabelValue "Players" "$($Draft.MaxPlayers)" Gray
    Write-LabelValue "Port" "UDP $($Draft.Port)" Gray
    Write-LabelValue "Cheats" "$($Draft.Cheats)" Gray
    Write-LabelValue "Speed" "$($Draft.PlayerSpeed)" Gray
    Write-LabelValue "Gravity" "$($Draft.Gravity)" Gray
    Write-LabelValue "Knockback" "$($Draft.Knockback)" Gray
    Write-LabelValue "Respawn" "$($Draft.WeaponRespawn) sec weapons" Gray
    Write-Host ""
    Write-Host "  Map rotation note: one map stays there; multiple maps rotate after the timelimit." -ForegroundColor DarkGray
    Write-Host "  Gameplay values apply after Apply rebuilds config and restarts the server." -ForegroundColor DarkGray
    if ($Message) {
        Write-Host ""
        Write-Host "  $Message" -ForegroundColor Magenta
    }
}
# inside game settings
function Show-GameSettingsScreen($Draft, [string]$Message = "") {
    Clear-Host
    Write-Host ""
    Write-Host "  GAME SETTINGS" -ForegroundColor Cyan
    Write-Host "  =====================================" -ForegroundColor DarkCyan
    Write-LabelValue "Resolution" "$($Draft.ResolutionWidth)x$($Draft.ResolutionHeight)" Cyan
    Write-LabelValue "Fullscreen" "$($Draft.Fullscreen)" Gray
    Write-LabelValue "Color bits" "$($Draft.ColorBits)" Gray
    Write-LabelValue "Texture bits" "$($Draft.TextureBits)" Gray
    Write-LabelValue "Compression" "$($Draft.TextureCompression)" Gray
    Write-LabelValue "Texture mode" "$($Draft.TextureMode)" Gray
    Write-LabelValue "Picmip" "$($Draft.PicMip)" Gray
    Write-LabelValue "Fast sky" "$($Draft.FastSky)" Gray
    Write-LabelValue "Console" "$($Draft.ConsoleEnabled)" Gray
    Write-LabelValue "Developer" "$($Draft.DeveloperMode)" Gray
    Write-LabelValue "FOV cvar" "$($Draft.Fov)" Gray
    Write-Host ""
    Write-Host "  Widescreen uses r_mode -1 plus custom width/height." -ForegroundColor DarkGray
    Write-Host "  Sky/texture cleanup uses safe config toggles only; no DLL hex patching." -ForegroundColor DarkGray
    Write-Host "  If the game is open, restart MOHAA after applying video settings." -ForegroundColor DarkGray
    if ($Message) {
        Write-Host ""
        Write-Host "  $Message" -ForegroundColor Magenta
    }
}
# Map settings and rotation
function Edit-MapRotation($Draft) {
    Clear-Host
    Write-Host ""
    Write-Host "  MAP QUEUE" -ForegroundColor Cyan
    Write-Host "  Enter maps separated by commas." -ForegroundColor DarkGray
    Write-Host "  Example: dm/mohdm6, dm/mohdm7, dm/mohdm1" -ForegroundColor DarkGray
    Write-Host "  Current: $(Get-MapList $Draft)" -ForegroundColor Gray
    $value = Read-Host "  New map queue, blank keeps current"
    if (-not [string]::IsNullOrWhiteSpace($value)) {
        $maps = @($value.Split(",") | ForEach-Object { $_.Trim() } | Where-Object { $_ })
        if ($maps.Count -gt 0) { $Draft.MapRotation = $maps }
    }
}

function Edit-SettingsTui($CurrentSettings) {
    $draft = Normalize-Settings (Copy-Settings $CurrentSettings)
    $message = ""

    while ($true) {
        Show-SettingsScreen $draft $message
        $items = @(
            [pscustomobject]@{ Label = "[N] Server name"; Hotkey = "N"; Action = "Name" }
            [pscustomobject]@{ Label = "[P] Password"; Hotkey = "P"; Action = "Password" }
            [pscustomobject]@{ Label = "[M] Map queue / rotation"; Hotkey = "M"; Action = "Maps" }
            [pscustomobject]@{ Label = "[T] Time limit"; Hotkey = "T"; Action = "Time" }
            [pscustomobject]@{ Label = "[X] Max players"; Hotkey = "X"; Action = "Players" }
            [pscustomobject]@{ Label = "[O] Port"; Hotkey = "O"; Action = "Port" }
            [pscustomobject]@{ Label = "[H] Cheats 0/1"; Hotkey = "H"; Action = "Cheats" }
            [pscustomobject]@{ Label = "[F] Player speed"; Hotkey = "F"; Action = "Speed" }
            [pscustomobject]@{ Label = "[G] Gravity"; Hotkey = "G"; Action = "Gravity" }
            [pscustomobject]@{ Label = "[K] Knockback"; Hotkey = "K"; Action = "Knockback" }
            [pscustomobject]@{ Label = "[W] Weapon respawn"; Hotkey = "W"; Action = "Respawn" }
            [pscustomobject]@{ Label = "[A] Apply and restart"; Hotkey = "A"; Action = "Apply" }
            [pscustomobject]@{ Label = "[C] Cancel"; Hotkey = "C"; Action = "Cancel" }
        )

        $action = Invoke-ArrowMenu $items "Settings: arrows + Enter, then A to apply or C to cancel."
        switch ($action) {
            "Name" { $draft.ServerName = Read-SettingText "Server name" $draft.ServerName; $message = "Server name updated in draft." }
            "Password" { $draft.Password = Read-SettingText "Password, blank means no password" $draft.Password; $message = "Password updated in draft." }
            "Maps" { Edit-MapRotation $draft; $message = "Map queue updated in draft." }
            "Time" { $draft.TimeLimit = Read-SettingInt "Time limit in minutes" $draft.TimeLimit 1 180; $message = "Time limit updated in draft." }
            "Players" { $draft.MaxPlayers = Read-SettingInt "Max players" $draft.MaxPlayers 1 64; $message = "Max players updated in draft." }
            "Port" { $draft.Port = Read-SettingInt "UDP port" $draft.Port 1024 65535; $message = "Port updated in draft." }
            "Cheats" { $draft.Cheats = Read-SettingInt "Cheats, 0 off or 1 on" $draft.Cheats 0 1; $message = "Cheats updated in draft." }
            "Speed" { $draft.PlayerSpeed = Read-SettingInt "Player speed, 320 is default" $draft.PlayerSpeed 100 1000; $message = "Player speed updated in draft." }
            "Gravity" { $draft.Gravity = Read-SettingInt "Gravity, 800 is default" $draft.Gravity 100 2000; $message = "Gravity updated in draft." }
            "Knockback" { $draft.Knockback = Read-SettingInt "Knockback, 1000 is default" $draft.Knockback 0 5000; $message = "Knockback updated in draft." }
            "Respawn" { $draft.WeaponRespawn = Read-SettingInt "Weapon respawn seconds" $draft.WeaponRespawn 0 120; $message = "Weapon respawn updated in draft." }
            "Apply" { return [pscustomobject]@{ Applied = $true; Settings = (Normalize-Settings $draft) } }
            "Cancel" { return [pscustomobject]@{ Applied = $false; Settings = $CurrentSettings } }
        }
    }
}

function Edit-GameSettingsTui($CurrentSettings) {
    $draft = Normalize-Settings (Copy-Settings $CurrentSettings)
    $message = ""

    while ($true) {
        Show-GameSettingsScreen $draft $message
        $items = @(
            [pscustomobject]@{ Label = "[1] 1080p widescreen preset"; Hotkey = "1"; Action = "Preset1080" }
            [pscustomobject]@{ Label = "[2] 1440p widescreen preset"; Hotkey = "2"; Action = "Preset1440" }
            [pscustomobject]@{ Label = "[R] Custom resolution"; Hotkey = "R"; Action = "Resolution" }
            [pscustomobject]@{ Label = "[F] Fullscreen 0/1"; Hotkey = "F"; Action = "Fullscreen" }
            [pscustomobject]@{ Label = "[T] Texture quality bits"; Hotkey = "T"; Action = "TextureBits" }
            [pscustomobject]@{ Label = "[X] Texture compression 0/1"; Hotkey = "X"; Action = "Compression" }
            [pscustomobject]@{ Label = "[Q] Texture sharpness picmip"; Hotkey = "Q"; Action = "PicMip" }
            [pscustomobject]@{ Label = "[S] Skybox cleanup preset"; Hotkey = "S"; Action = "SkyFix" }
            [pscustomobject]@{ Label = "[V] FOV cvar"; Hotkey = "V"; Action = "Fov" }
            [pscustomobject]@{ Label = "[A] Apply game settings"; Hotkey = "A"; Action = "Apply" }
            [pscustomobject]@{ Label = "[C] Cancel"; Hotkey = "C"; Action = "Cancel" }
        )
        #Presets Going in (Make it easier for the user)
        $action = Invoke-ArrowMenu $items "Game settings: arrows + Enter, then A to apply or C to cancel."
        switch ($action) {
            "Preset1080" {
                $draft.ResolutionWidth = 1920
                $draft.ResolutionHeight = 1080
                $draft.Fullscreen = 1
                $draft.ColorBits = 32
                $draft.TextureBits = 32
                $draft.PicMip = 0
                $message = "1080p widescreen preset selected."
            }
            "Preset1440" {
                $draft.ResolutionWidth = 2560
                $draft.ResolutionHeight = 1440
                $draft.Fullscreen = 1
                $draft.ColorBits = 32
                $draft.TextureBits = 32
                $draft.PicMip = 0
                $message = "1440p widescreen preset selected."
            }
            "Resolution" {
                $draft.ResolutionWidth = Read-SettingInt "Resolution width" $draft.ResolutionWidth 640 7680
                $draft.ResolutionHeight = Read-SettingInt "Resolution height" $draft.ResolutionHeight 480 4320
                $message = "Resolution updated in draft."
            }
            "Fullscreen" { $draft.Fullscreen = Read-SettingInt "Fullscreen, 0 off or 1 on" $draft.Fullscreen 0 1; $message = "Fullscreen updated in draft." }
            "TextureBits" { $draft.TextureBits = Read-SettingInt "Texture bits, usually 32" $draft.TextureBits 16 32; $message = "Texture bits updated in draft." }
            "Compression" { $draft.TextureCompression = Read-SettingInt "Texture compression, 0 off or 1 on" $draft.TextureCompression 0 1; $message = "Texture compression updated in draft." }
            "PicMip" { $draft.PicMip = Read-SettingInt "Picmip, 0 sharpest, higher is blurrier" $draft.PicMip 0 5; $message = "Picmip updated in draft." }
            "SkyFix" {
                $draft.FastSky = 0
                $draft.TextureCompression = 0
                $draft.TextureBits = 32
                $draft.ColorBits = 32
                $draft.PicMip = 0
                $draft.TextureMode = "gl_linear_mipmap_linear"
                $message = "Skybox cleanup preset selected: fast sky off, compression off, 32-bit textures."
            }
            "Fov" { $draft.Fov = Read-SettingInt "FOV cvar, 90 is conservative" $draft.Fov 80 120; $message = "FOV cvar updated in draft." }
            "Apply" { return [pscustomobject]@{ Applied = $true; Settings = (Normalize-Settings $draft) } }
            "Cancel" { return [pscustomobject]@{ Applied = $false; Settings = $CurrentSettings } }
        }
    }
}

$settings = Read-Settings
$startResult = Start-Server $settings -ForceConfig:$RegenerateConfig
$process = $startResult.Process
$configState = $startResult.ConfigState

Show-Dashboard $settings $process $configState

if ($NoMenu) {
    exit 0
}

$message = ""
while ($true) {
    $menu = @(
        [pscustomobject]@{ Label = "[G] Open MOHAA"; Hotkey = "G"; Action = "Game" }
        [pscustomobject]@{ Label = "[C] Copy friend command"; Hotkey = "C"; Action = "Copy" }
        [pscustomobject]@{ Label = "[E] Server settings"; Hotkey = "E"; Action = "Settings" }
        [pscustomobject]@{ Label = "[V] Game settings"; Hotkey = "V"; Action = "GameSettings" }
        [pscustomobject]@{ Label = "[R] Restart server"; Hotkey = "R"; Action = "Restart" }
        [pscustomobject]@{ Label = "[B] Rebuild config"; Hotkey = "B"; Action = "Build" }
        [pscustomobject]@{ Label = "[S] Stop server"; Hotkey = "S"; Action = "Stop" }
        [pscustomobject]@{ Label = "[Q] Quit launcher"; Hotkey = "Q"; Action = "Quit" }
    )

    $action = Invoke-ArrowMenu $menu
    switch ($action) {
        "Game" { $message = Open-Game $settings }
        "Copy" { $message = Copy-FriendCommand }
        "Settings" {
            $result = Edit-SettingsTui $settings
            if ($result.Applied) {
                $settings = $result.Settings
                Save-Settings $settings
                Stop-Server $settings
                $startResult = Start-Server $settings -ForceConfig
                $process = $startResult.Process
                $configState = $startResult.ConfigState
                $message = "Settings applied, config rebuilt, server restarted."
            } else {
                $message = "Settings canceled. No changes applied."
            }
        }
        "GameSettings" {
            $result = Edit-GameSettingsTui $settings
            if ($result.Applied) {
                $settings = $result.Settings
                Save-Settings $settings
                $message = Apply-GameSettings $settings
            } else {
                $message = "Game settings canceled. No changes applied."
            }
        }
        "Restart" {
            Stop-Server $settings
            $startResult = Start-Server $settings
            $process = $startResult.Process
            $configState = $startResult.ConfigState
            $message = "Server restarted."
        }
        "Build" {
            Stop-Server $settings
            $startResult = Start-Server $settings -ForceConfig
            $process = $startResult.Process
            $configState = $startResult.ConfigState
            $message = "Config rebuilt and server restarted." 
        }
        "Stop" {
            Stop-Server $settings
            $process = $null
            $message = "Server stopped." #Stoping the MOHAA_server
        }
        "Quit" {
            Clear-Host
            Write-Host ""
            Write-Host "  IMUSTAFSKI Server Runner closed." -ForegroundColor Cyan
            Write-Host "  Server process is unchanged. Use Stop server before Quit if you want to stop hosting." -ForegroundColor DarkGray
            exit 0
        } #Quiting Existing from the terminal at all not to the cmd main
    }

    Show-Dashboard $settings (Get-ServerProcess $settings | Select-Object -First 1) $configState $message
}
